### PR TITLE
Adding font suggestions

### LINKED ISSUE #21: Use Google font
- Add other Google fonts to style.md and decide which one to use
- Cartoonish font looks great for the logo

### PR DESCRIPTION
**Pull request by Sukrittt**
* Addressing issue #21
* Adding `.png` files to provide you with cartoonish font suggestions.
* After you decide which font to use, I can integrate that font into your portfolio website.
* Folder path - `/public/fonts`
* To explore more fonts like these, visit https://www.fontfabric.com/display/

### CODE REVIEW

**Comment by Haywayaheadshot** [comment]
@Sukrittt Thank you for working on this issue. Can you add the fonts to some of the pages?

**Comment by Sukrittt** [comment]
Sure, have you chosen any of the fonts I suggested?

**Comment by Haywayaheadshot** [comment]
> Sure, have you chosen any of the fonts I suggested?

Not yet. I was hoping we use them each on different pages and decide on which one to use.

**Comment by Sukrittt** [comment]
* Your name at the top can use a cartoonish font.
* Everything else can be kept in the same font.

**Comment by Haywayaheadshot** [comment]
> * Your name at the top can use a cartoonish font.
> * Everything else can be kept in the same font.

I agree with you. The logo name should remain as it is. 

But what I am saying is that you should try these fonts on different pages so we can see how they look.

**Comment by Sukrittt** [comment]
Okay, I'll make changes in the fonts and make a pull request.

**Comment by Sukrittt** [comment]
Hey,
I came across an issue while trying to make changes to the code in your GitHub repository. The problem is that the code was written on a different operating system and I am getting errors as a result.

If you could make the following changes to the `App.css` file or any other `.css` file, you can use this font-family:

```
@font-face {
  font-family: Muller-Next;
  src: url(../../public/MullerNextExpandedTrial-Regular.ttf);
}

/* Wherever you want to use this text */
body{
  font-family: Muller-Next;
}
```

Note: I have already added font-family Muller-Next `.ttf ` file in `/public`.

**Comment by Haywayaheadshot** [comment]
@Sukrittt Thank you for contributing to this project. With the fonts that was used before, a link was added to the public/index.html as you can see below.

https://github.com/Haywayaheadshot/abu-the-portfolio/blob/6cb0ae69d579026159975460355bc6d25ee9236b/public/index.html#L14-L17

And then I added a class that will call the font family so I can use them in the react components. Below is the class for the font-family.

https://github.com/Haywayaheadshot/abu-the-portfolio/blob/6cb0ae69d579026159975460355bc6d25ee9236b/src/styles/index.css#L20-L22

Could you please use that approach or add the font to the index.css file?

It is easier and simpler to use these methods.

**Review by Haywayaheadshot — CHANGES_REQUESTED** [review]
@Sukrittt Thank you for contributing to this project. With the fonts that was used before, a link was added to the public/index.html as you can see below.

https://github.com/Haywayaheadshot/abu-the-portfolio/blob/6cb0ae69d579026159975460355bc6d25ee9236b/public/index.html#L14-L17

And then I added a class that will call the font family so I can use them in the react components. Below is the class for the font-family.

https://github.com/Haywayaheadshot/abu-the-portfolio/blob/6cb0ae69d579026159975460355bc6d25ee9236b/src/styles/index.css#L20-L22

Could you please use that approach or add the font to the index.css file?

It is easier and simpler to use these methods.

**Comment by Sukrittt** [comment]
Indeed, that approach appears feasible. However, as previously mentioned, I am unable to modify the code due to the fact that it was created on a different operating system and is causing compilation errors on my current system.

**Comment by Haywayaheadshot** [comment]
@Sukrittt I am sorry about your predicament. I will go ahead and finish the task. Thank you for your contribution.

**Pull request closed without merging**
